app:
  defaultData: true

server:
  servlet:
    contextPath: /api/v1
  port: 8991

springdoc:
  api-docs:
    path: /api-docs

spring:
  datasource:
    driverClassName: org.h2.Driver
    username: username
    password: password
    url: "jdbc:h2:mem:testdb"
  jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true